### PR TITLE
Added PrometheusRemoteWriteExporter

### PR DESCRIPTION
**Pull request by mangulonr**

### CODE REVIEW

**Review by DavSanchez — APPROVED** [review]

**Review by rubenruizdegauna — CHANGES_REQUESTED** [review]
Tests are failing. Please take a look :)

**Comment by mangulonr** [comment]
I just updated the exporter version to v0.33.0 according to 
https://pkg.go.dev/go.opentelemetry.io/collector@v0.33.0/exporter/prometheusremotewriteexporter

Let me know if this is ok

**Comment by DavSanchez** [comment]
Same issue 😞 `unknown revision exporter/prometheusremotewriteexporter/v0.109.0`

**Comment by DavSanchez** [comment]
Let me check from my side, I'll open a PR similar to this one and trigger the pipelines from there.

**Comment by DavSanchez** [comment]
Close via #121

**Pull request closed without merging**
