### PR TITLE
NR-86915 feat: add default config for nr-otel-collector

### PR DESCRIPTION
**Pull request by rogercoll**
This configuration is used for feature parity with the New Relic Infrastructure Agent.

### CODE REVIEW

**Comment by rogercoll** [comment]
Should we use `NEW_RELIC_OTLP_ENDPOINT` or `OTEL_EXPORTER_OTLP_ENDPOINT` as the public documentation denotes? https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic/

**Comment by rogercoll** [comment]
What do you think of adding into the configuration the [ballast extension](https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/ballastextension)? It is recommended while using the memory_limiter processor: https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor

**Comment by rogercoll** [comment]
> Should we use `NEW_RELIC_OTLP_ENDPOINT` or `OTEL_EXPORTER_OTLP_ENDPOINT` as the public documentation denotes? https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic/

`OTEL_EXPORTER_OTLP_ENDPOINT` is used in New Relic documentation (APMs, Otel, etc.), removing `NEW_RELIC_OTLP_ENDPOINT`

**Review by rubenruizdegauna — APPROVED** [review]
LGTM 🔥🔥🔥

**Pull request merged**
